Pass option for websocket endpoint
Ashlar/binance-api-node pull request #278
Opened 2020-09-20 05:24 UTC by djheru

This PR adds options in the Binance constructor to pass a parameter `wsBase` which, like the `httpBase` param for the REST API, sets the websocket endpoint.

The goal here is to allow the library to be used with Binance.us

2020-09-21 16:16 UTC, balthazar requested changes
Thanks for the PR :slightly_smiling_face: 

Rather than reassigning the endpoints object properties you will have to pass down the endpoint url to each of the functions, it should make it cleaner

2021-01-16 07:59 UTC, Pi12345678 approved these changes

2021-01-31 08:37 UTC, jorisw commented
@djheru Resolving the conflicts in this PR may help speed up merging

2021-01-31 08:41 UTC, jorisw commented
Dupe of #283

2021-01-31 19:36 UTC, closed without merging