feat: Added margin repay endpoint
Ashlar/binance-api-node pull request #299
Opened 2020-11-29 11:36 UTC by gelito

Added a new endpoint for repaying at margin trading.

Added also the interface.

I didn't attach test because you only be able to test it if you have assets with borrow or interests to repay.

2020-12-23 18:08 UTC, balthazar requested changes
Thanks for the PR! Can you also add the doc in the readme?

2020-12-23 18:08 UTC, balthazar commented on index.d.ts
> +
Can you remove that

2020-12-28 23:20 UTC, gelito commented
Added the doc in the readme.  I created a new section, `margin`, but I didn't include all previous methods.

2020-12-31 22:51 UTC, balthazar commented
Thanks!

2020-12-31 22:51 UTC, merged