support https proxy
Ashlar/binance-api-node pull request #410
Opened 2021-05-13 04:49 UTC by kawais

support https proxy in options
const client = Binance( {
    apiKey: 'xxx',
    apiSecret: 'xxx',
    httpsProxy: 'http://127.0.0.1:1080'
} )

2021-05-13 15:42 UTC, balthazar requested changes

2021-05-13 15:42 UTC, balthazar commented on index.d.ts
> +    httpsProxy?: string
can you call that `proxy`?

2021-05-13 15:42 UTC, balthazar commented on package.json
> +    "https-proxy-agent": "^5.0.0",
this has been unmaintained for a year now, is there another solution?

2021-05-13 15:42 UTC, balthazar commented on src/http-client.js
> +  let opt = {
`const` and call it `opts`

2021-05-13 15:42 UTC, balthazar commented on src/http-client.js
> +  }
newline

2021-05-13 15:42 UTC, balthazar commented on src/http-client.js
> +  if (httpsProxy) opt.agent = new proxyAgent(httpsProxy)
use brackets, even for single lines

2021-05-13 15:42 UTC, balthazar commented on src/http-client.js
> +    if (httpsProxy) opt.agent = new proxyAgent(httpsProxy)
avoid duplicating statements, this logic should be put in a function

2021-05-13 15:42 UTC, balthazar commented on src/open-websocket.js
> +    ...proxyOpt
I dont see an option on reconnecting-websocket for a proxy, are you sure about this?

2021-05-14 02:55 UTC, kawais commented
It's better to use https://github.com/gajus/global-agent.
so this pr is not necessary.

2021-11-11 14:37 UTC, balthazar commented
Closing in favor of #513

2021-11-11 14:37 UTC, closed without merging