add futuresAllMarkPrices
Ashlar/binance-api-node pull request #441
Opened 2021-06-06 13:28 UTC by hp8wvvvgnj6asjm7

2021-06-06 18:07 UTC, balthazar requested changes

2021-06-06 18:07 UTC, balthazar commented on src/websocket.js
> +
neat: remove this newline

2021-06-06 18:07 UTC, balthazar commented on src/websocket.js
> +
that one too

2021-06-06 21:09 UTC, hp8wvvvgnj6asjm7 commented
ẙ̗õ̖͔̬̰͚̝̩̌̆̒̏͛̆ͥ̋ͅͅu̟̺̝͎͈̘̤͉̹̰͚͕͍̣̦̣̰̰ͦ͌̊ͣ̉ͨ̔̄̏̈́̑ͧ̋̀ͨͯͣ̚'̼̪͚̹͍̰̭͔̺̗̺̝̫̻͈͈̥͍̳̜̼̬̓̅ͤ̇̓ͦ͑ͬ̄͂͊̃͒͗̓̂ͦͥ̏̓͋͐ͩͣ̏̚ͅͅͅͅr̞̝̻̰̤̦̘̱͎̘̖̩̟̬̝̰̝͍̹̫̫̹̼̼̖̹̟̫̜͇̗͚̪̙͊͊̇ͤͫ̐͂̑̒͗̉̆̈̽̃ͭ͆̌͆ͦ̉̿ͭ̑̃̎ͨ̎̌ͯ͂ͫ͋̐ͥͅe͍̪̯͈̖͎̯̝̱̼̲̖̦͍̜͕̯̫̦͖̪̙̬̮̭̣̩̥͙̣̪̝̜̼̟̭̱͓͚̬̭͉ͫ͒ͫͥ̎ͭ͆ͤͮ͛̐̃̉ͤ̊̾̊̌͂ͨͭͫ͌͋̊̇͒͌ͥͧͭ̾̒ͪͪͫͬ̍ͥͤ̄ͣͤͅ ̱͚̟̳̥͔̤͈̝̞̳̤̲̲̫̰̥̳̟̫̞̰͓͉̻̰͙͈͙̪͍̟̭̼̱̝̬̱̥͓̫̝̳̫̘̣͓͔̣̠͂ͧ̿ͯͭ̌̊ͯ̐̑̇ͪ̂̊̈́̉̅̄͒̂̾̐̾ͣ̎͋͐ͫ͊̅̂̽ͧͯ̍̏̑͊̔́ͯ̎͋̇̇̎̀ͦ̈͊̚̚ͅͅẁ̗͎̝͍͎̯͖̗̦̩͇̭̙̣͓͈͍̪̩̜̜̜̞̪͕͚̘͕͚͈̱̯̼̪̮̝̙͖̞͎̮̺̮̯̩̦̘̜̤̲͎̺͇͍̦̻̲͔̬͈͚̔̓ͤͯ͌͋ͬ̍̋̿̎͋̓͐̊͒̃̊̎̇̈́̀͐ͯ̄̊̿͗̾̽̓̔́ͮ̆̓ͨͤ̾̃͑̐̀͂͗̒͊̉̓ͣ̽̓́̓ͤ͌͂ͨ̚̚ẻ͉̱͚͕̦̮̦̬̟̳͔͈͙̰̭̭͍̠̟̞͔͕̺̝̠̦̝̺̫̞̬̘̳̝͍͎̦̭̪̲̞͉̻̲̘̠͈̫̱̳̜ͥ̌͆̓̑̅̇̍̽̆̊ͥ́̅ͥ̊̿́̑ͪ͊̂͂̍̔̃̀͑̀ͧ̀ͧ͌ͬͧ͗ͨ͊ͯ͌͋ͭ̽͋̿ͯ̔̾ͬ͗́ͅl͇̩͉̼͓̳̤͕̜̥̠̝͚̩̝̟̣̥͓͔̩͚͚̟̖̯͇͙̻̙̻̥̫̼͇̮̦̗̮̺̝̾͊ͪ́̉̋͂̏ͬ̓̾ͩͧ̃̊ͨ̎̈̈̅ͬͤͣͮ̆̋͐̊̃ͩ̾̅̓̋̃̐̈́ͫ̓͌̊̆̚ͅͅc̩̱̤͚̤͖̩̜̼̼͍̤͉̞̖͙̮̟̙̫̻̼̦̪͙̥̥̤͎͇̦̯͚̞̯͗̓̈̅ͯ̔̈́ͤ̒ͫͪ̍̍̌͌̎ͯͬ͒̓ͩ̒̽ͣ̌̐̇ͮ̇̅̒̇͒͊̚o̥̝̙̰͙͙̫͚͈̪̟̠̙̤̣͕̻̙̭̜͚̝͙͕͈͔̓̂̅̑̔͊͑̆̆̊ͥ̃̌͊̔ͥ͒̇͋ͩ̅̊̽̍ͬ͛m͚̺͔̬̞̗̖̪̺͖͉̤̭̪̗̣̤̲̓ͬ̈͋̈ͭͪ̔̏̿̊̄ͯ̽̀ͭ͑̂e̺͚̼̺̝̫̤̙̠̓̓ͪ̽ͪ̀̾̋̚

2021-06-11 16:14 UTC, balthazar commented on src/websocket.js
> +  return options => cache.close(1000, 'Close handle was called', { keepClosed: true, ...options })
Add a newline on top of this line

2021-06-11 16:14 UTC, balthazar commented on src/websocket.js
> +  const variant = payload.updateSpeed === '1s' ? '!markPrice@arr@1s' : '!markPrice@arr'
can't the update speed also be 3s? or is that the default one?

2021-07-04 03:32 UTC, itman85 commented
@hp8wvvvgnj6asjm7 please check request change to continue process this PR, we need it merge soon. thank you a lot

2021-11-11 14:39 UTC, merged