Add maginGetOrder
Ashlar/binance-api-node pull request #464
Opened 2021-06-27 17:15 UTC by krolov

Hi @balthazar 
I hope you are doing good.

I add a new method - marginGetOrder.

Also, I fixed several things:
- Add marginOrder description to README.md
- Remove double assetDetail from http-client.js
- For isIsolated field, I add `string | boolean` type. According to Binance documentation it must be string, but Binance kindly accepts boolean too. So I keep boolean for back compability.

2021-06-27 19:36 UTC, balthazar requested changes
Just minor tweak on the readme, but everything looks good otherwise! Thanks!

2021-06-27 19:36 UTC, balthazar commented on README.md
> +  - [marginGetOrder](#margingetorder)
could you make the link camelcase too?

2021-06-27 19:36 UTC, balthazar commented on README.md
> +| newClientOrderId  | NuStringmber  | false    | A unique id among open orders. Automatically generated if not sent.
invalid type

2021-06-27 19:36 UTC, balthazar commented on src/http-client.js
> -    assetDetail: payload => privCall('/sapi/v1/asset/assetDetail', payload),
good catch!

2021-06-28 10:09 UTC, krolov commented
@balthazar  fixed

2021-06-28 12:54 UTC, krolov commented
Also I made `transactTime` for `Order` optional. It exists only if this object returns after new order functions.

2021-06-28 16:10 UTC, balthazar commented
Sounds good, thanks again :)

2021-06-28 16:10 UTC, merged