added dustLog method
Ashlar/binance-api-node pull request #486
Opened 2021-08-16 20:38 UTC by ichbtm

hi here is a pull request to add dustLog (/sapi/v1/asset/dribblet) to the api

2021-08-17 14:13 UTC, balthazar requested changes

2021-08-17 14:13 UTC, balthazar commented on README.md
> +	- [dustLog](#dustlog)
can you fix the indentation on this?

2021-08-18 07:23 UTC, ichbtm commented on README.md
> +	- [dustLog](#dustlog)
done

2021-08-18 14:58 UTC, merged

2021-08-18 14:58 UTC, balthazar commented
Thank you!

2021-08-20 22:45 UTC, ichbtm commented
it was a pleasure ;)